# The URL the site will be built for
base_url = "https://bitdevs-la.org"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

generate_rss = true

title = "BitDevs LA"

[extra]
# Put all your custom variables here

github_url = "https://github.com"
menu = ["item1","item2","item3"]
meetup = "https://www.meetup.com/SoCal-Lightning"